# Generated by Django 2.0 on 2020-02-23 11:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='namat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Shared_clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=datetime.datetime(2020, 2, 23, 11, 14, 10, 765458, tzinfo=utc))),
                ('expire_date', models.DateTimeField(default=datetime.datetime(2020, 2, 23, 11, 14, 10, 765507, tzinfo=utc))),
                ('start_rate', models.CharField(max_length=75)),
                ('customer_rate', models.CharField(max_length=75)),
                ('bank', models.CharField(default='Demir', max_length=100)),
                ('client', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='clients.ApplyClient')),
            ],
        ),
    ]
