# Generated by Django 2.0 on 2020-02-29 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shared_clients',
            name='client',
        ),
        migrations.DeleteModel(
            name='Shared_clients',
        ),
    ]
