# Generated by Django 2.0 on 2020-02-15 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documents', models.FileField(blank=True, default='/media/index.jpeg', upload_to='media')),
            ],
        ),
        migrations.RemoveField(
            model_name='bank',
            name='documents',
        ),
        migrations.AddField(
            model_name='feedfile',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='managers.Bank'),
        ),
    ]
