# Generated by Django 2.0 on 2020-02-23 11:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0002_namat_shared_clients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='namat',
        ),
        migrations.AlterField(
            model_name='shared_clients',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 11, 15, 11, 245147, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shared_clients',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 11, 15, 11, 245101, tzinfo=utc)),
        ),
    ]
