# Generated by Django 2.0 on 2020-03-02 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0002_auto_20200229_1023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
