# Generated by Django 2.0 on 2020-02-16 12:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0002_auto_20200215_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientApplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealTime', models.DateField(default=datetime.datetime(2020, 2, 16, 12, 17, 9, 588609, tzinfo=utc))),
                ('credit_purpose', models.CharField(max_length=100)),
                ('credit_amount', models.CharField(max_length=100)),
                ('collateral', models.CharField(max_length=200)),
                ('credit_history', models.CharField(max_length=200)),
                ('finan_perfor', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='clientapplay',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='managers.Client'),
        ),
    ]
