# Generated by Django 2.0 on 2020-02-24 04:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0003_auto_20200223_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='shared_clients',
            name='state',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='shared_clients',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 24, 4, 19, 44, 112867, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shared_clients',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 24, 4, 19, 44, 112818, tzinfo=utc)),
        ),
    ]
