# Generated by Django 2.0 on 2020-02-16 12:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0003_auto_20200216_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientapplay',
            name='dealTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 16, 12, 18, 18, 697802, tzinfo=utc)),
        ),
    ]
