# Generated by Django 2.0 on 2020-02-24 04:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0004_auto_20200223_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shared_clients',
            name='state',
        ),
        migrations.AlterField(
            model_name='shared_clients',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 24, 4, 25, 30, 893719, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shared_clients',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 24, 4, 25, 30, 893674, tzinfo=utc)),
        ),
    ]
