# Generated by Django 2.0 on 2020-02-16 12:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0004_auto_20200216_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientapplay',
            name='dealTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
