# Generated by Django 2.0 on 2020-02-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0005_auto_20200223_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shared_clients',
            name='expire_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='shared_clients',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
