# Generated by Django 2.0 on 2020-02-16 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0005_auto_20200216_0621'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientApplay',
            new_name='ApplayClient',
        ),
    ]
