# Generated by Django 2.0 on 2020-02-16 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0006_auto_20200216_0631'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApplayClient',
            new_name='ApplyClient',
        ),
    ]
