# Generated by Django 2.0 on 2020-02-24 05:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0006_auto_20200223_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shared_clients',
            name='expire_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='shared_clients',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
