# Generated by Django 2.0 on 2020-02-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0007_auto_20200223_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='shared_clients',
            name='percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
