# Generated by Django 2.0 on 2020-02-26 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=100)),
                ('receiving_date', models.DateTimeField()),
                ('return_date', models.DateTimeField()),
                ('maturity_date', models.DateTimeField()),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('currency_unit', models.CharField(max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
    ]
