# Generated by Django 2.0.1 on 2020-03-10 05:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField()),
                ('password', models.CharField(default=None, max_length=128, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_client', models.BooleanField(default=False)),
                ('is_bank', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.AlterField(
            model_name='acceptclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Register'),
        ),
        migrations.AlterField(
            model_name='basicinformation',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.Register'),
        ),
        migrations.AlterField(
            model_name='business',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.Register'),
        ),
        migrations.AlterField(
            model_name='collateral',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.Register'),
        ),
        migrations.AlterField(
            model_name='credit_history',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.Register'),
        ),
        migrations.AlterField(
            model_name='credit_line',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.Register'),
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.Register'),
        ),
        migrations.AlterField(
            model_name='works',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.Register'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
