# Generated by Django 2.0 on 2020-02-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyclient',
            name='state',
            field=models.BooleanField(default=0),
        ),
    ]
