# Generated by Django 2.0 on 2020-02-28 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_credit_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='works',
            old_name='documents',
            new_name='certificate',
        ),
        migrations.AlterField(
            model_name='business',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.Client'),
        ),
        migrations.AlterField(
            model_name='collateral',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.Client'),
        ),
        migrations.AlterField(
            model_name='credit_history',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.Client'),
        ),
        migrations.AlterField(
            model_name='credit_line',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.Client'),
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.Client'),
        ),
        migrations.AlterField(
            model_name='works',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.Client'),
        ),
    ]
