# Generated by Django 2.0 on 2020-02-24 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_applyclient_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=100)),
                ('spouse_name', models.CharField(max_length=100)),
                ('dependant', models.CharField(max_length=100)),
                ('birth_date', models.CharField(max_length=100)),
                ('birth_palce', models.CharField(max_length=100)),
                ('passport_no', models.CharField(max_length=100)),
                ('issued_by', models.CharField(max_length=100)),
                ('issued_date', models.CharField(max_length=100)),
                ('register_place', models.CharField(max_length=100)),
                ('residential_add', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('inn', models.CharField(max_length=100)),
                ('contacts', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
    ]
