# Generated by Django 2.0 on 2020-02-28 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20200228_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicinformation',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='collateral',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='credit_history',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='credit_line',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='guarantee',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='works',
            options={'ordering': ['-id']},
        ),
    ]
