# Generated by Django 2.0.1 on 2020-03-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20200310_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='message',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
