# Generated by Django 2.0.1 on 2020-03-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20200311_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
    ]
