# Generated by Django 2.0 on 2020-02-29 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20200229_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptcleint',
            name='collateral',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.Collateral'),
        ),
        migrations.AlterField(
            model_name='acceptcleint',
            name='credit_history',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.Credit_History'),
        ),
        migrations.AlterField(
            model_name='acceptcleint',
            name='credit_line',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.Credit_line'),
        ),
    ]
