# Generated by Django 2.0 on 2020-03-01 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_auto_20200229_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='state',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='acceptcleint',
            name='credit_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Credit_line'),
        ),
    ]
