# Generated by Django 2.0 on 2020-03-02 11:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0002_auto_20200229_1023'),
        ('clients', '0009_auto_20200301_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expire_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_rate', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
                ('collateral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Collateral')),
                ('credit_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Credit_History')),
                ('credit_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Credit_line')),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managers.Bank')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
        migrations.RemoveField(
            model_name='acceptcleint',
            name='client',
        ),
        migrations.RemoveField(
            model_name='acceptcleint',
            name='collateral',
        ),
        migrations.RemoveField(
            model_name='acceptcleint',
            name='credit_history',
        ),
        migrations.RemoveField(
            model_name='acceptcleint',
            name='credit_line',
        ),
        migrations.AlterModelOptions(
            name='applyclient',
            options={},
        ),
        migrations.RemoveField(
            model_name='applyclient',
            name='client',
        ),
        migrations.RemoveField(
            model_name='applyclient',
            name='collateral',
        ),
        migrations.RemoveField(
            model_name='applyclient',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='applyclient',
            name='credit_amount',
        ),
        migrations.RemoveField(
            model_name='applyclient',
            name='credit_history',
        ),
        migrations.RemoveField(
            model_name='applyclient',
            name='credit_purpose',
        ),
        migrations.RemoveField(
            model_name='applyclient',
            name='dealTime',
        ),
        migrations.RemoveField(
            model_name='applyclient',
            name='finan_perfor',
        ),
        migrations.RemoveField(
            model_name='applyclient',
            name='state',
        ),
        migrations.DeleteModel(
            name='AcceptCleint',
        ),
    ]
