# Generated by Django 2.0 on 2020-03-02 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_auto_20200302_0509'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplyClient',
        ),
        migrations.AlterField(
            model_name='acceptclient',
            name='credit_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Credit_line'),
        ),
    ]
