# Generated by Django 2.0 on 2020-03-02 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_auto_20200302_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptclient',
            name='credit_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Credit_line'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.AcceptClient'),
        ),
    ]
