# Generated by Django 2.0 on 2020-03-02 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_auto_20200302_0519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='client',
            new_name='accept_client',
        ),
        migrations.AlterField(
            model_name='acceptclient',
            name='credit_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Credit_line'),
        ),
    ]
